class SBurgersTestData:
    REGISTRATION_NAME = "Alex"
    REGISTRATION_EMAIL = "AlexanderDneprov7014@yandex.ru"
    REGISTRATION_PASSWORD_6_NUMBERS = "123456"
    REGISTRATION_PASSWORD_5_NUMBERS = "12345"